import { createRequire } from "node:module";

const { version: PACKAGE_VERSION } = createRequire(import.meta.url)(
  "../package.json",
);

const REPO_RAW_BASE =
  "https://raw.githubusercontent.com/luizssantiago92/spec-driven-harness";

/** Assets are fetched from the tag matching the installed CLI version. */
export const PINNED_REF = `v${PACKAGE_VERSION}`;

/** Used only when the pinned tag is not published yet. */
export const FALLBACK_REF = "main";

export const REPO_RAW_URL = `${REPO_RAW_BASE}/${PINNED_REF}`;

export const FALLBACK_REPO_URL = `${REPO_RAW_BASE}/${FALLBACK_REF}`;

export const SKILL_DIRS = [".cursor/skills", ".claude/skills"];

export const CURSOR_RULES_DIR = ".cursor/rules";

export const REFERENCES_SUBDIR = "references";

export const HARNESS_SCRIPTS_DIR = ".specs/harness/scripts";

/** @type {{ file: string, remotePath: string }[]} */
export const SKILL_ASSETS = [
  {
    file: "agent-architecture.md",
    remotePath: "skills/agent-architecture.md",
  },
  {
    file: "engineering-standards.md",
    remotePath: "skills/engineering-standards.md",
  },
  {
    file: "security-review.md",
    remotePath: "skills/security-review.md",
  },
  {
    file: "git-handoff.md",
    remotePath: "skills/git-handoff.md",
  },
  {
    file: "task-graph-engineering.md",
    remotePath: "skills/task-graph-engineering.md",
  },
];

/** Phase procedures loaded on demand by the hub skill. */
/** @type {{ file: string, remotePath: string }[]} */
export const REFERENCE_ASSETS = [
  { file: "specify.md", remotePath: "skills/references/specify.md" },
  { file: "discuss.md", remotePath: "skills/references/discuss.md" },
  { file: "design.md", remotePath: "skills/references/design.md" },
  { file: "tasks.md", remotePath: "skills/references/tasks.md" },
  { file: "implement.md", remotePath: "skills/references/implement.md" },
  { file: "validate.md", remotePath: "skills/references/validate.md" },
  { file: "memory.md", remotePath: "skills/references/memory.md" },
  { file: "quick-mode.md", remotePath: "skills/references/quick-mode.md" },
  { file: "context-limits.md", remotePath: "skills/references/context-limits.md" },
  { file: "lessons.md", remotePath: "skills/references/lessons.md" },
];

/** Deterministic gates executed with python3. */
/** @type {{ file: string, remotePath: string }[]} */
export const SCRIPT_ASSETS = [
  { file: "_common.py", remotePath: "scripts/_common.py" },
  { file: "validate_spec.py", remotePath: "scripts/validate_spec.py" },
  { file: "validate_tasks.py", remotePath: "scripts/validate_tasks.py" },
  { file: "validate_state.py", remotePath: "scripts/validate_state.py" },
  { file: "check_commit.py", remotePath: "scripts/check_commit.py" },
  { file: "lessons.py", remotePath: "scripts/lessons.py" },
];

/** @type {{ file: string, remotePath: string }[]} */
export const RULE_ASSETS = [
  {
    file: "engineering-baseline.mdc",
    remotePath: "rules/engineering-baseline.mdc",
  },
];

export const STATE_HEADER = `# 📝 Project State & Decisions

## Active Feature
- Feature: —
- Phase: —
- Branch: —

## Next Step (single item)
- [ ] —

## Blockers
- none

## Deferred Ideas
- none

## Decisions
`;

export const LESSONS_HEADER = `# Lessons Learned

Generated by \`lessons.py\` from \`.specs/lessons.json\`. Do not edit this file.
A clean PASS records nothing. Only **confirmed** lessons below are guidance.
Inspect candidates with \`python3 .specs/harness/scripts/lessons.py list --status all\`.

- none yet
`;

export const CURSORRULES_MARKER_BEGIN = "<!-- AGENTIC-HARNESS:BEGIN -->";

export const CURSORRULES_MARKER_END = "<!-- AGENTIC-HARNESS:END -->";

export const CURSORRULES_BLOCK = `${CURSORRULES_MARKER_BEGIN}
# Execution Contract (Agentic Harness)
When planning architecture, specs, or multi-step features, read the hub first:
- \`.cursor/skills/agent-architecture.md\` — SDD hub: contract, phases, gates, complexity router
- \`.cursor/skills/references/\` — phase procedures (specify, discuss, design, tasks, implement, validate, memory, quick-mode, context-limits, lessons)
- \`.cursor/skills/task-graph-engineering.md\` — task DAG, parallelism, verify topology
- \`.cursor/skills/engineering-standards.md\` — secure coding, code quality, artifact language
- \`.cursor/skills/security-review.md\` — security checklist for /verify
- \`.cursor/skills/git-handoff.md\` — git sync and session handoff for .specs/

Deterministic gates (python3, non-zero exit means STOP):
- \`.specs/harness/scripts/validate_spec.py\` before confirming a spec
- \`.specs/harness/scripts/validate_tasks.py\` before approving tasks
- \`.specs/harness/scripts/check_commit.py\` on each commit
- \`.specs/harness/scripts/validate_state.py\` before declaring a feature done
- \`.specs/harness/scripts/lessons.py\` to record or load grounded lessons

All project artifacts are written in English.
Persistent state: \`.specs/STATE.md\` (decisions/handoff) and \`.specs/LESSONS.md\` (lessons learned).
Project rules: \`.cursor/rules/engineering-baseline.mdc\`
${CURSORRULES_MARKER_END}
`;

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);

/**
 * Assets become executable gate scripts on disk, so the source has to be
 * trustworthy. Plain HTTP is rejected except against a local host, which the
 * test suite uses.
 *
 * @param {string} base
 * @returns {string} the validated base, without a trailing slash
 */
export function assertSafeAssetBase(base) {
  let url;

  try {
    url = new URL(base);
  } catch {
    throw new Error(`Invalid harness asset URL: ${base}`);
  }

  const isLocal = LOCAL_HOSTS.has(url.hostname);

  if (url.protocol === "https:" || (url.protocol === "http:" && isLocal)) {
    return base.replace(/\/+$/, "");
  }

  throw new Error(
    `Refusing to download harness assets over ${url.protocol}//${url.hostname} ` +
      "— only HTTPS sources are allowed. Harness assets include executable gate scripts.",
  );
}

/** @returns {string | undefined} the override base, when one is configured */
export function resolveAssetOverride() {
  const override = process.env.HARNESS_REPO_URL;
  return override ? assertSafeAssetBase(override) : undefined;
}

/**
 * @param {string} remotePath
 * @param {string} [repoUrl]
 */
export function resolveAssetUrl(remotePath, repoUrl) {
  const base = assertSafeAssetBase(
    repoUrl ?? resolveAssetOverride() ?? REPO_RAW_URL,
  );
  return `${base}/${remotePath}`;
}
